// This file was generated by RedwoodJS
import * as Cell from './DataCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindDataById, FindDataByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './DataCell'

type CellInputs = CellProps<SuccessType, FindDataById, typeof Cell, FindDataByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
