// This file was generated by RedwoodJS
import * as Cell from './EditContactCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditContactById, EditContactByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditContactCell'

type CellInputs = CellProps<SuccessType, EditContactById, typeof Cell, EditContactByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
