// This file was generated by RedwoodJS
import ExplorePageType from 'C:/VERCEL/chatgpt/web/src/pages/ExplorePage/ExplorePage'
import FatalErrorPageType from 'C:/VERCEL/chatgpt/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from 'C:/VERCEL/chatgpt/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HelperPageType from 'C:/VERCEL/chatgpt/web/src/pages/HelperPage/HelperPage'
import HomepagePageType from 'C:/VERCEL/chatgpt/web/src/pages/HomepagePage/HomepagePage'
import LoginPageType from 'C:/VERCEL/chatgpt/web/src/pages/LoginPage/LoginPage'
import MembersPageType from 'C:/VERCEL/chatgpt/web/src/pages/MembersPage/MembersPage'
import ModulesPageType from 'C:/VERCEL/chatgpt/web/src/pages/ModulesPage/ModulesPage'
import NotFoundPageType from 'C:/VERCEL/chatgpt/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from 'C:/VERCEL/chatgpt/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from 'C:/VERCEL/chatgpt/web/src/pages/SignupPage/SignupPage'
import Store2PageType from 'C:/VERCEL/chatgpt/web/src/pages/Store2Page/Store2Page'
import Store3PageType from 'C:/VERCEL/chatgpt/web/src/pages/Store3Page/Store3Page'
import ContactContactPageType from 'C:/VERCEL/chatgpt/web/src/pages/Contact/ContactPage/ContactPage'
import ContactContactsPageType from 'C:/VERCEL/chatgpt/web/src/pages/Contact/ContactsPage/ContactsPage'
import ContactEditContactPageType from 'C:/VERCEL/chatgpt/web/src/pages/Contact/EditContactPage/EditContactPage'
import ContactNewContactPageType from 'C:/VERCEL/chatgpt/web/src/pages/Contact/NewContactPage/NewContactPage'
import UserEditUserPageType from 'C:/VERCEL/chatgpt/web/src/pages/User/EditUserPage/EditUserPage'
import UserNewUserPageType from 'C:/VERCEL/chatgpt/web/src/pages/User/NewUserPage/NewUserPage'
import UserUserPageType from 'C:/VERCEL/chatgpt/web/src/pages/User/UserPage/UserPage'
import UserUsersPageType from 'C:/VERCEL/chatgpt/web/src/pages/User/UsersPage/UsersPage'

declare global {
  const ExplorePage: typeof ExplorePageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HelperPage: typeof HelperPageType
  const HomepagePage: typeof HomepagePageType
  const LoginPage: typeof LoginPageType
  const MembersPage: typeof MembersPageType
  const ModulesPage: typeof ModulesPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const Store2Page: typeof Store2PageType
  const Store3Page: typeof Store3PageType
  const ContactContactPage: typeof ContactContactPageType
  const ContactContactsPage: typeof ContactContactsPageType
  const ContactEditContactPage: typeof ContactEditContactPageType
  const ContactNewContactPage: typeof ContactNewContactPageType
  const UserEditUserPage: typeof UserEditUserPageType
  const UserNewUserPage: typeof UserNewUserPageType
  const UserUserPage: typeof UserUserPageType
  const UserUsersPage: typeof UserUsersPageType
}
