// This file was generated by RedwoodJS
import * as Cell from './EditUserCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditUserById, EditUserByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditUserCell'

type CellInputs = CellProps<SuccessType, EditUserById, typeof Cell, EditUserByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
