// This file was generated by RedwoodJS
import * as Cell from './EditDataCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditDataById, EditDataByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditDataCell'

type CellInputs = CellProps<SuccessType, EditDataById, typeof Cell, EditDataByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
