// This file was generated by RedwoodJS
import * as Cell from './DatasCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindDatas, FindDatasVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './DatasCell'

type CellInputs = CellProps<SuccessType, FindDatas, typeof Cell, FindDatasVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
